# Generated by Django 5.0.6 on 2024-07-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_customers', '0004_delete_customertempstatus'),
        ('servers', '0010_alter_botconfiginfo_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfigInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uuid', models.UUIDField(unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='BOT', max_length=20)),
                ('renew_count', models.IntegerField(default=0)),
                ('usage_limit', models.IntegerField(default=0)),
                ('days_limit', models.IntegerField(default=0)),
                ('start_timestamp', models.PositiveIntegerField(null=True)),
                ('user_limit', models.PositiveIntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BotEveryServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_now', models.PositiveIntegerField(null=True)),
                ('days_now', models.PositiveIntegerField(null=True)),
                ('update_timestamp', models.PositiveIntegerField(null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_config.botconfiginfo')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
        migrations.CreateModel(
            name='BotInfinitCongisLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_config.botconfiginfo')),
            ],
        ),
    ]
