# Generated by Django 5.0.6 on 2024-07-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0001_initial'),
        ('servers', '0011_remove_boteveryserver_config_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BotEveryServer',
            new_name='BotConfigsEveryServerUsage',
        ),
    ]
