# Generated by Django 5.0.6 on 2024-07-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0002_rename_boteveryserver_botconfigseveryserverusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiginfo',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
