# Generated by Django 5.0.6 on 2024-07-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0003_botconfiginfo_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botconfigseveryserverusage',
            name='days_now',
        ),
        migrations.AlterField(
            model_name='botconfigseveryserverusage',
            name='usage_now',
            field=models.FloatField(null=True),
        ),
    ]
