# Generated by Django 5.0.6 on 2024-07-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0004_remove_botconfigseveryserverusage_days_now_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiginfo',
            name='user_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botconfigseveryserverusage',
            name='usage_now',
            field=models.FloatField(default=0),
        ),
    ]
