# Generated by Django 5.0.6 on 2024-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0005_alter_botconfiginfo_user_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiginfo',
            name='update',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
