# Generated by Django 5.0.6 on 2024-07-20 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0011_remove_boteveryserver_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellersConfigInfo',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('usage_limit', models.IntegerField(default=0)),
                ('days_limit', models.IntegerField(default=0)),
                ('user_limit', models.IntegerField(default=0)),
                ('start_timestamp', models.IntegerField(null=True)),
                ('enable', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfinitCongisLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sellers_config.sellersconfiginfo')),
            ],
        ),
        migrations.CreateModel(
            name='SellerConfigsEveryServerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_now', models.FloatField(default=0)),
                ('update_timestamp', models.PositiveIntegerField(null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers_config.sellersconfiginfo')),
            ],
        ),
    ]
