# Generated by Django 5.0.6 on 2024-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersconfiginfo',
            name='bot_user',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
