# Generated by Django 5.0.6 on 2024-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_config', '0002_sellersconfiginfo_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersconfiginfo',
            name='renew_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
