# Generated by Django 5.0.6 on 2024-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_config', '0003_sellersconfiginfo_renew_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersconfiginfo',
            name='update',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
