# Generated by Django 5.0.6 on 2024-07-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_config',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='finanace_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='list_configs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
