# Generated by Django 5.0.6 on 2024-07-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_create_config_user_finanace_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_config',
            new_name='create_config_acc',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='list_configs',
            new_name='list_configs_acc',
        ),
    ]
