# Generated by Django 5.0.6 on 2024-07-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_create_config_user_create_config_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_config_acc',
            field=models.BooleanField(default=True),
        ),
    ]
