# Generated by Django 5.0.6 on 2024-07-23 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_delete_config_acc'),
        ('sellers_connection', '0002_bots_bot_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bot',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sellers_connection.bots'),
        ),
    ]
