# Generated by Django 5.0.6 on 2024-07-14 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('ID', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('proxy_path', models.CharField(max_length=30, null=True)),
                ('port', models.IntegerField(null=True)),
                ('server_domain', models.CharField(max_length=50, null=True, unique=True)),
                ('fake_domain', models.CharField(max_length=50, null=True)),
                ('admin_uuid', models.UUIDField(null=True)),
                ('sellers_single_uuid', models.UUIDField(null=True)),
                ('sellers_sub_uuid', models.UUIDField(null=True)),
                ('bot_single_uuid', models.UUIDField(null=True)),
                ('bot_sub_uuid', models.UUIDField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('old_iphone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BotSubscriptionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uuid', models.UUIDField(unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='BotSubConfigsCreateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'in queue'), (1, 'pending server'), (2, 'done'), (-1, 'error')], default=0)),
                ('update_timestamp', models.PositiveIntegerField(default=0)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.botsubscriptioninfo')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
        migrations.CreateModel(
            name='BotConfigInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uuid', models.UUIDField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
    ]
