# Generated by Django 5.0.6 on 2024-07-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsubscriptioninfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='botconfiginfo',
            name='server',
        ),
        migrations.RemoveField(
            model_name='server',
            name='bot_single_uuid',
        ),
        migrations.RemoveField(
            model_name='server',
            name='sellers_single_uuid',
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='created_by',
            field=models.CharField(default='BOT', max_length=20),
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='renew_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BotInfinitCongisLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servers.botconfiginfo')),
            ],
        ),
        migrations.DeleteModel(
            name='BotSubConfigsCreateStatus',
        ),
        migrations.DeleteModel(
            name='BotSubscriptionInfo',
        ),
    ]
