# Generated by Django 5.0.6 on 2024-07-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_remove_botsubscriptioninfo_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEveryServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_limit', models.PositiveIntegerField(null=True)),
                ('usage_now', models.PositiveIntegerField(null=True)),
                ('days_limit', models.PositiveIntegerField(null=True)),
                ('days_now', models.PositiveIntegerField(null=True)),
                ('user_limit', models.PositiveIntegerField(null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.botconfiginfo')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server')),
            ],
        ),
    ]
