# Generated by Django 5.0.6 on 2024-07-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_boteveryserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='boteveryserver',
            name='update_timestamp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
