# Generated by Django 5.0.6 on 2024-07-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_boteveryserver_update_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boteveryserver',
            name='days_limit',
        ),
        migrations.RemoveField(
            model_name='boteveryserver',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='boteveryserver',
            name='user_limit',
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='days_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='usage_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botconfiginfo',
            name='user_limit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
