# Generated by Django 5.0.6 on 2024-07-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_remove_boteveryserver_days_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiginfo',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
