# Generated by Django 5.0.6 on 2024-07-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_alter_botconfiginfo_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfiginfo',
            old_name='days_limit',
            new_name='endtime_timestamp',
        ),
    ]
