# Generated by Django 5.0.6 on 2024-07-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_rename_days_limit_botconfiginfo_endtime_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botconfiginfo',
            old_name='endtime_timestamp',
            new_name='start_timestamp',
        ),
    ]
