# Generated by Django 5.0.6 on 2024-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_rename_endtime_timestamp_botconfiginfo_start_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfiginfo',
            name='days_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='server',
            name='last_update',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
