# Generated by Django 5.0.6 on 2024-07-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0004_delete_customertempstatus'),
        ('servers', '0009_botconfiginfo_days_limit_server_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfiginfo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer'),
        ),
    ]
