# Generated by Django 5.0.6 on 2024-07-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_finance', '0003_alter_confirmtamdidpaymentqueue_config_and_more'),
        ('bot_reports', '0005_alter_configlog_config'),
        ('servers', '0010_alter_botconfiginfo_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boteveryserver',
            name='config',
        ),
        migrations.RemoveField(
            model_name='botinfinitcongislimit',
            name='config',
        ),
        migrations.RemoveField(
            model_name='boteveryserver',
            name='server',
        ),
        migrations.DeleteModel(
            name='BotConfigInfo',
        ),
        migrations.DeleteModel(
            name='BotInfinitCongisLimit',
        ),
        migrations.DeleteModel(
            name='BotEveryServer',
        ),
    ]
