# Generated by Django 5.0.6 on 2024-07-20 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSellrsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_seller', to=settings.AUTH_USER_MODEL)),
                ('parent_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
