# Generated by Django 5.0.6 on 2024-07-20 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellersPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_limit', models.PositiveIntegerField()),
                ('expire_limit', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('user_limit', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerprice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
