# Generated by Django 5.0.6 on 2024-07-15 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_customers', '0004_delete_customertempstatus'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_off', models.BooleanField()),
                ('amount', models.PositiveIntegerField()),
                ('customer_count', models.PositiveIntegerField()),
                ('use_count', models.PositiveIntegerField()),
                ('create_timestamp', models.PositiveBigIntegerField()),
                ('end_timestamp', models.PositiveBigIntegerField()),
                ('for_infinit_usages', models.BooleanField()),
                ('for_infinit_times', models.BooleanField()),
                ('for_not_infinity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_limit', models.PositiveIntegerField()),
                ('expire_limit', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('user_limit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmPaymentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_price', models.PositiveIntegerField()),
                ('config_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config_in_queue', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('deny_reseon', models.CharField(blank=True, max_length=100, null=True)),
                ('config_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('timestamp', models.PositiveBigIntegerField(default=0)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmTamdidPaymentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_price', models.PositiveIntegerField()),
                ('config_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('deny_reseon', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.PositiveBigIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.botconfiginfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserActiveOffCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
                ('off_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_finance.offcodes')),
            ],
        ),
    ]
