# Generated by Django 5.0.6 on 2024-07-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0004_delete_customertempstatus'),
        ('bot_finance', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpaymentqueue',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'waiting for upload picture'), (1, 'waiting for confirmation'), (2, 'first confirme'), (3, 'second confirm'), (10, 'denied')], default=0),
        ),
        migrations.AlterField(
            model_name='confirmtamdidpaymentqueue',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'waiting for upload picture'), (1, 'waiting for confirmation'), (2, 'first confirme'), (3, 'second confirm'), (10, 'denied')], default=0),
        ),
        migrations.AlterField(
            model_name='offcodes',
            name='type_off',
            field=models.IntegerField(choices=[(0, 'amount'), (1, 'percent')]),
        ),
        migrations.CreateModel(
            name='CreateConfigQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_uuid', models.UUIDField(unique=True)),
                ('config_name', models.CharField(max_length=50, unique=True)),
                ('usage_limit', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('user_limit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sent_to_user', models.IntegerField(choices=[(0, 'Created'), (1, 'pending'), (2, 'sent'), (5, 'Faild')], default=0)),
                ('pay_status', models.PositiveSmallIntegerField(choices=[(0, 'waiting for pay img'), (1, 'waiting for confirm'), (2, 'first confirmed'), (3, 'secoend confirm'), (10, 'denied')], default=0)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TamdidConfigQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_limit', models.IntegerField()),
                ('expire_time', models.IntegerField()),
                ('user_limit', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sent_to_user', models.IntegerField(choices=[(0, 'Created'), (1, 'pending'), (2, 'sent'), (5, 'Faild')], default=0)),
                ('pay_status', models.PositiveSmallIntegerField(choices=[(0, 'waiting for pay img'), (1, 'waiting for confirm'), (2, 'first confirmed'), (3, 'secoend confirm'), (10, 'denied')], default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.botconfiginfo')),
            ],
        ),
    ]
