# Generated by Django 5.0.6 on 2024-07-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0001_initial'),
        ('bot_finance', '0002_alter_confirmpaymentqueue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmtamdidpaymentqueue',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_config.botconfiginfo'),
        ),
        migrations.AlterField(
            model_name='tamdidconfigqueue',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_config.botconfiginfo'),
        ),
    ]
