# Generated by Django 5.0.6 on 2024-07-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(10, 'Succes'), (0, 'Created'), (1, 'Pending'), (-1, 'Faild'), (-10, 'Cancelled'), (-2, 'Banned')], default=0)),
                ('created_timestamp', models.PositiveIntegerField(default=0)),
                ('updated_timestamp', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
            ],
        ),
    ]
