# Generated by Django 5.0.6 on 2024-07-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotErrorLog',
        ),
    ]
