# Generated by Django 5.0.6 on 2024-07-16 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0004_delete_customertempstatus'),
        ('bot_reports', '0003_initial'),
        ('servers', '0002_remove_botsubscriptioninfo_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=15)),
                ('action', models.TextField()),
                ('timestamp', models.IntegerField(default=1719482579)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.IntegerField(default=1719482579)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.botconfiginfo')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.IntegerField(default=1719482579)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
            ],
        ),
    ]
