# Generated by Django 5.0.6 on 2024-07-18 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0001_initial'),
        ('bot_reports', '0004_adminlog_configlog_customerlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configlog',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_config.botconfiginfo'),
        ),
    ]
