# Generated by Django 5.0.6 on 2024-07-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('chatid', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=32, null=True)),
                ('wallet', models.IntegerField(default=0)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
    ]
