# Generated by Django 5.0.6 on 2024-07-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='chatid',
            new_name='chat_id',
        ),
    ]
