# Generated by Django 5.0.6 on 2024-07-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0002_rename_chatid_customer_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pay_temp_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='temp_status',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='test_config',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerTempStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_status', models.CharField(default='normal', max_length=30)),
                ('pay_temp_amount', models.PositiveIntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot_customers.customer')),
            ],
        ),
    ]
