# Generated by Django 5.0.6 on 2024-07-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_customers', '0003_customer_pay_temp_amount_customer_temp_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerTempStatus',
        ),
    ]
