# Generated by Django 5.0.6 on 2024-07-23 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers_connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bots',
            name='bot_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
